### ISSUE TITLE
Is this project similar to qemu's coroutine-gthread?

### ISSUE THREAD

**Issue by Akagi201** [elmarco/gcoroutine#1]
My base project is based on glib, and I want to add coroutine support.

So, I found your project and qemu's coroutine, both based on glib.

<https://github.com/qemu/qemu/blob/master/util/coroutine-gthread.c>

Do you have some suggestions? Which one should I choose?

**Comment by elmarco** [comment]
Hi,

gcoroutine is based on qemu coroutine implementation. So https://github.com/qemu/qemu/blob/master/util/coroutine-gthread.c is similar to https://github.com/elmarco/gcoroutine/blob/master/src/gcoroutine-gthread.c.

Currently, gcoroutine isn't being released nor used by any project that I know of. There was some attempt to make qemu (spice-gtk & vnc) to use gcoroutine, but this was discontinued, since some qemu maintainers are still doing some implementation changes and believe it can't be abstracted away today.

I would suggest you to copy gcoroutine implementation in your project for the time being, it is likely going to be easier than taking qemu's coroutine implementation.

**Comment by Akagi201** [comment]
@elmarco Thanks, I got it. I will try to use gcoroutine in my project.
